// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

//go:build wasm
// +build wasm

package main

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmvmhost"
	"github.com/ntsd/iscp-lottery/src/iscplotterycontract/go/iscplotterycontract"
)

func main() {
}

func init() {
	wasmvmhost.ConnectWasmHost()
}

//export on_call
func onCall(index int32) {
	iscplotterycontract.OnLoad(index)
}

//export on_load
func onLoad() {
	iscplotterycontract.OnLoad(-1)
}
