// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package iscplotterycontract

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "iscplotterycontract"
	ScDescription = "ISCPLotteryContract description"
	HScName       = wasmlib.ScHname(0x884f32dd)
)

const (
	ParamNumber   = "number"
	ParamOwner    = "owner"
	ParamRoundIdx = "roundIdx"
)

const (
	ResultOwner   = "owner"
	ResultRound   = "round"
	ResultTickets = "tickets"
)

const (
	StateCurrentRoundIdx = "currentRoundIdx"
	StateHistoryTickets  = "historyTickets"
	StateOwner           = "owner"
	StateRounds          = "rounds"
	StateTickets         = "tickets"
)

const (
	FuncCreateTicket        = "createTicket"
	FuncDraw                = "draw"
	FuncGetMyHistoryTickets = "getMyHistoryTickets"
	FuncGetMyTickets        = "getMyTickets"
	FuncInit                = "init"
	FuncSetOwner            = "setOwner"
	ViewGetCurrentRound     = "getCurrentRound"
	ViewGetOwner            = "getOwner"
	ViewGetRound            = "getRound"
)

const (
	HFuncCreateTicket        = wasmlib.ScHname(0x7a6044ef)
	HFuncDraw                = wasmlib.ScHname(0x436fe402)
	HFuncGetMyHistoryTickets = wasmlib.ScHname(0x2d7c6667)
	HFuncGetMyTickets        = wasmlib.ScHname(0x12d805ce)
	HFuncInit                = wasmlib.ScHname(0x1f44d644)
	HFuncSetOwner            = wasmlib.ScHname(0x2a15fe7b)
	HViewGetCurrentRound     = wasmlib.ScHname(0x7abd711b)
	HViewGetOwner            = wasmlib.ScHname(0x137107a6)
	HViewGetRound            = wasmlib.ScHname(0xbea7b465)
)
